### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by davodego** [movim/movim#134]
Hi, I'm new with movim. I installed the server, all goes well.
When I try to login with my jabber account, it shows the Connecting notice and nothing more. 
php.log shows me thr following two errors:

[21-Feb-2016 12:22:27 Europe/London] PHP Warning:  Invalid argument supplied for foreach() in /var/www/movim/app/widgets/Login/Login.php on line 228
[21-Feb-2016 12:22:43 Europe/London] DNS request failed: The domain name referenced in the query does not exist.

Movim Server output is:
Encrypted 
mYrjTXBhYEX29nUqJuQ1tvOzEfQCOvGp : 149 connected
mYrjTXBhYEX29nUqJuQ1tvOzEfQCOvGp widgets before : 2.8546600 MB
mYrjTXBhYEX29nUqJuQ1tvOzEfQCOvGp widgets : 4.1956024 MB
mYrjTXBhYEX29nUqJuQ1tvOzEfQCOvGp : 149 deconnected
mYrjTXBhYEX29nUqJuQ1tvOzEfQCOvGp : 205 connected

How can I solve this?

Ubuntu 14.04 LTS with Apache 2.4.7 and PHP 2.5.0.

**Comment by edhelas** [comment]
Well looks like you have a DNS issue ;) What is your XMPP server ?

**Comment by davodego** [comment]
My XMPP Server is my own on the same host. Reachable via dynDNS at jabber.srvdg.de. Its an ejabberd 15.07.

**Comment by edhelas** [comment]
I've removed a Google DNS dependencies, does this has fixed your issue ?

**Comment by davodego** [comment]
Sorry for late answer, my server crashed so i have to setup all new :(

I have done a git pull, but i have no change. Log still says:
[13-Mar-2016 11:59:47 Europe/Berlin] DNS request failed: The domain name referenced in the query does not exist.
[13-Mar-2016 11:59:47 Europe/Berlin] DNS request failed: The domain name referenced in the query does not exist.
[13-Mar-2016 11:59:47 Europe/Berlin] PHP Notice:  Undefined index: HTTP_EMAIL in /var/www/movim/app/widgets/Login/Login.php on line 97

**Comment by davodego** [comment]
My jabber url is jabber.srvdg.de. I've tried to connect at pod.movim.eu too, but also no luck.
I have a second account at jabber.aventer.biz. With that account I can login on my movim server, and on pod.movim.eu. 
jabber.srvdg.de is a dynDNS Adress to a home Server. 
Any other solution? 
Sould I configre a reverse DNS entry for my local DNS Server?

**Comment by edhelas** [comment]
I see that you don't have any DNS records configured for your XMPP server https://kingant.net/check_xmpp_dns/?h=jabber.srvdg.de. But it's also a bug in Movim, can you please create me a test account on your server then I can debug ?

**Comment by davodego** [comment]
Sure, your username is: edhelas with pwd: movim

**Comment by edhelas** [comment]
Thanks, I'll have a look at it asap.

**Comment by edhelas** [comment]
Well everything seems perfectly fine, it's just that PHP is not able to enable the TLS connection in XMPP. Seems to be deeper than Movim :/

**Comment by davodego** [comment]
where can I look for a solution?
php.ini? ejabberd?

**Comment by edhelas** [comment]
No it seems that I'll have to open a bug report to PHP. But I have to be sure.

**Comment by edhelas** [comment]
Hi, also I've just remarked this 

> Ubuntu 14.04 LTS with Apache 2.4.7 and PHP 2.5.0.
> Is it PHP 5.2 ? If yes, it's a really old version that Movim doesn't supports.

**Comment by davodego** [comment]
Oh, 2.5.0 was the version of ZendEngine.
Ubuntu 14.04, with php 5.5.9 and apache 2.4.7. ist correct.

I've had a hdd crash some time ago and i setup the server new. I will try movim again and give feedback soon.

**Comment by davodego** [comment]
I followed the install instructions, server started without errors.
I can not access the server with the jid of my own server on the same host.
Log shows:
[10-Jun-2016 06:42:05 Europe/Berlin] PHP Notice:  Undefined property: stdClass::$size in /var/www/movim/vendor/movim/modl/src/Modl/SmartDB.php on line 317
[10-Jun-2016 06:42:06 Europe/Berlin] PHP Notice:  Undefined property: stdClass::$size in /var/www/movim/vendor/movim/modl/src/Modl/SmartDB.php on line 317
[10-Jun-2016 06:44:05 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /var/www/movim/app/widgets/Login/Login.php on line 243

I cann access the server with login settings from another account on a host outside. 
:(

**Comment by edhelas** [comment]
Hi, did you have some updates on this issue ?

**Comment by davodego** [comment]
No, it's all the same. I installed all new. I can't connect to my jabber server. I just can connect to a jabber server outside my lan :)

Are there any users running movim successful in there lan?

**Comment by edhelas** [comment]
The issue is the DNS resolver I think. Did you try to precise the IP of your internal XMPP server in the `/etc/hosts` of your internal Movim server ?

**Comment by davodego** [comment]
/etc/hosts

```
127.0.0.1       localhost
127.0.1.1       srvdg.local    
192.168.1.2     dienste.srvdg.de
192.168.1.2     jabber.srvdg.de
```

**Comment by davodego** [comment]
I've installed all new again and recreate the db. 
Now the above error is gone.
Log is clean but movim web UI says: 
"Huch! XMPP-Legitimierung ist fehlgeschlagen"
(auth fail)

ejabberd.log

```
2016-07-03 11:16:08.396 [info] <0.467.0>@ejabberd_listener:accept:299 (#Port<0.12516>) Accepted connection ::FFFF:192.168.1.2:59834 -> ::FFFF:192.168.1.2:5222
2016-07-03 11:16:08.483 [debug] <0.10033.0>@ejabberd_receiver:process_data:349 Received XML on stream = <<"<stream:stream xmlns:stream=\"http://etherx.jabber.org/streams\" version=\"1.0\" xmlns=\"jabber:client\" to=\"jabber.srvdg.de\">">>
2016-07-03 11:16:08.483 [debug] <0.10034.0>@ejabberd_c2s:send_text:1922 Send XML on stream = <<"<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='2644173226' from='jabber.srvdg.de' version='1.0' xml:lang='de'>">>

2016-07-03 11:16:08.484 [debug] <0.10034.0>@ejabberd_c2s:send_text:1922 Send XML on stream = <<"<stream:features><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='tRd4XMJSw6lNM0CpWa5zvZ9Ca8Y='/><register xmlns='http://jabber.org/features/iq-register'/><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features>">>

2016-07-03 11:16:08.492 [debug] <0.10033.0>@ejabberd_receiver:process_data:349 Received XML on stream = <<"<auth xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\" mechanism=\"SCRAM-SHA-1\">\n                    biwsbj1kYW5pZWwscj0rd1VRY3VhNDhpNWVncTByZUQ4Z2VBTWRJNVBuUmZmamZGNVNhTzBzZGFnPQ==\n                </auth>">>
2016-07-03 11:16:08.492 [debug] <0.10033.0>@shaper:update:120 State: {maxrate,1000,0.0,1467537368483613}, Size=196
M=98.0, I=8.88

2016-07-03 11:16:08.492 [debug] <0.10034.0>@ejabberd_c2s:send_text:1922 Send XML on stream = <<"<challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj0rd1VRY3VhNDhpNWVncTByZUQ4Z2VBTWRJNVBuUmZmamZGNVNhTzBzZGFnPVlIazNVazhabUFUaGpWWHZIa3czT1E9PSxzPTZDM3p0QkgzcTJHSXRrbnVXbmVXWnc9PSxpPTQwOTY=</challenge>">>
2016-07-03 11:16:08.583 [debug] <0.10033.0>@ejabberd_receiver:process_data:349 Received XML on stream = <<"<response xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\"></response>">>
2016-07-03 11:16:08.583 [debug] <0.10033.0>@shaper:update:120 State: {maxrate,1000,990.339140628158,1467537368582569}, Size=62
M=61.40675794699336, I=0.602

2016-07-03 11:16:08.583 [debug] <0.10034.0>@ejabberd_c2s:send_text:1922 Send XML on stream = <<"<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><bad-protocol/></failure>">>
2016-07-03 11:16:28.388 [debug] <0.10033.0>@ejabberd_receiver:process_data:349 Received XML on stream = <<"</stream:stream>">>
```

**Comment by edhelas** [comment]
Looks like a SASL auth issues, are you sure about your credentials ?

**Comment by davodego** [comment]
Yes, I'm sure :) Log in with them all the time.

**Comment by davodego** [comment]
Now the web UI can't connect to server.

```
Movim daemon launched
Base URI : https://dienste.srvdg.de/movim/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8002/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8002/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
    proxy_redirect off;
}

Encrypted
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 180 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 180 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 235 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 235 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 244 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 244 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 259 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 259 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 268 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 268 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 283 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 283 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 292 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 292 deconnected
```

and so on...

**Comment by edhelas** [comment]
Ok I've just updated Movim and Moxl, can you please try again and check the daemon logs (it should tell you the resolved IP)

**Comment by davodego** [comment]
I lunched movim:

```
Movim daemon launched
Base URI : https://dienste.srvdg.de/movim/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8002/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8002/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
    proxy_redirect off;
}

Encrypted
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 181 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM widgets before : 2.8479309 MB
miXniNDq0kobEB7SCC4OXOo6di0AGjmM widgets : 4.3088837 MB
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : Connection to jabber.srvdg.de (192.168.1.2)
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker launched
miXniNDq0kobEB7SCC4OXOo6di0AGjmM launched : 5.4858856 MB
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : linker killed
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 181 deconnected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM : 237 connected
miXniNDq0kobEB7SCC4OXOo6di0AGjmM widgets before : 2.8479309 MB
miXniNDq0kobEB7SCC4OXOo6di0AGjmM widgets : 4.3088837 MB
```

Nothing in php.log an logger.log
ejabberd.log shows: 
2016-07-03 13:33:27.606 [debug] <0.10247.0>@ejabberd_c2s:send_text:1922 Send XML on stream = <<"<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><bad-protocol/></failure>">>

**Comment by davodego** [comment]
My password contains different symbols like " ; ", Could this make the error.

**Comment by edhelas** [comment]
Do you have PHP XDebug installed ? If yes, it cause crashes in the daemon (and huge slowdown).
For the password it should not be an issue.

**Comment by davodego** [comment]
I have installed XDebug now.
apache error.log is full of:
[Sun Jul 03 15:32:53.011811 2016] [authz_core:debug] [pid 18210] mod_authz_core.c(802): [client 127.0.0.1:36978] AH01626: authorization result of <RequireAny>: granted

Nothing in movim php.log and logger.log
Is there any other log to look at?

**Comment by edhelas** [comment]
No it's the opposite, XDebug should be uninstalled :D 
Can you pull from GIT again, I've fixed the latest error.

**Comment by davodego** [comment]
Ok, uninstall xdebug - done.
But the auth failure is still there.
This is in the php.log now:

```
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  13. Movim\Widget\Base->__() /var/www/movim/app/widgets/Api/Api.php:15
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  14. call_user_func_array:{/var/www/movim/src/Movim/Widget/Base.php:89}() /var/www/movim/src/Movim/Widget/Base.php:89
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  15. __() /var/www/movim/src/Movim/Widget/Base.php:89
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  16. Movim\i18n\Locale->translate() /var/www/movim/app/helpers/UtilsHelper.php:604
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  17. call_user_func_array:{/var/www/movim/src/Movim/i18n/Locale.php:111}() /var/www/movim/src/Movim/i18n/Locale.php:111
[03-Jul-2016 15:37:57 Europe/Berlin] PHP  18. sprintf() /var/www/movim/src/Movim/i18n/Locale.php:111
[03-Jul-2016 15:38:57 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
[03-Jul-2016 15:38:57 Europe/Berlin] PHP Notice:  Undefined index: scheme in /var/www/movim/src/Movim/Daemon/Core.php on line 64
[03-Jul-2016 15:40:37 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
[03-Jul-2016 15:40:37 Europe/Berlin] PHP Notice:  Undefined index: scheme in /var/www/movim/src/Movim/Daemon/Core.php on line 64
```

**Comment by davodego** [comment]
I changed ejabberd auth_method from scram to plain. No change, I still have the auth failure.
Login with jappix WebUI works without sasl login.

**Comment by davodego** [comment]
Something new, I turned on my cipher and certificate restrictions.
ejabberd log:
`2016-07-03 16:12:24.113 [error] <0.480.0>@ejabberd_receiver:handle_info:248 TLS error = SSL_do_handshake failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol`

**Comment by davodego** [comment]
There is something with my ssl config.
If I comment ouit ssl protocol_options:
 #protocol_options:
    #   - "no_sslv3"
    #   - "no_sslv2"
    #   - "no_tlsv1"
    #   - "no_tlsv1_1"
I become the: xmpp-sasl bad-protocol failure

If I activate the protocol_options i become the handshake failure.

Andy idea?

**Comment by edhelas** [comment]
From my local computer I can login on your XMPP server using SASL SCRAM-SHA-1 using Movim. 
I have no idea where this issue can be but there is chances that it comes from your internal network.
I'm sorry :/

**Comment by davodego** [comment]
My xmpp server runs behind a FritzBox router. Its conneced via dyndns to the internet.
Connections from outside come via dyndns, thru the router via port release to the server.
Could there be a problem with the ports?
In lan connection goes directly and not through the router.

**Comment by davodego** [comment]
I tried unencrypted.
php.log shows:

```
[03-Jul-2016 18:50:09 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
[03-Jul-2016 18:50:18 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
[03-Jul-2016 18:50:39 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
[03-Jul-2016 18:53:09 Europe/Berlin] PHP Notice:  Undefined index: host in /var/www/movim/src/Movim/Daemon/Core.php on line 62
```

maybe this helps?

**Comment by davodego** [comment]
I tried another account from my server. And tata it works. It must be the password that produced the error. The password with the symbol ; in it.

Update: confirmed. Registered new user with no special characters in pwd. It also works. Password handling is the problem.

**Comment by edhelas** [comment]
I tried the login with a lot of different password and was not able to reproduce the issue. Also the Login now supports specific characters in the JID (like accents). Closing the issue.
