### ISSUE TITLE
Too long a password during sign up sends your handle into the abyss

### ISSUE THREAD

**Issue by RedSnt** [movim/movim#1404]
Maybe I should've created my account first with a low character number, then changed it for a longer afterwards, but I tried to create an account with a 512 character password and I just got a "bad request" error, obviously because it was too long, but I was expecting to just get told what the limit was, perhaps 128 characters, but instead when I tried to put in a new password I got told that  the handle I had chosen had been registered - yet no confirmation mail arrived.  

But also, I messed up, should've kept better record of the passwords I was trying, because I immediately recreated a 256 character in KeePassXC which discarded my 512 password, and I'm just wondering if that handle is forever lost/locked in limbo or it will become available after a period of time because no confirmation email was clicked.  

Oh, and there's no way of resetting password, which makes sense for an account that both "exists" but also isn't confirmed.

**Comment by edhelas** [comment]
Send me your account by email and I'll recover it.
I'll put a password length limit during registration. 512 is way too long anyway, you never have to do something like that.

**Comment by RedSnt** [comment]
@edhelas Yeah, I'm a dumbass for trying that. I emailed you directly. Maybe I should've PM'ed the movim mastadon account?

**Comment by edhelas** [comment]
There was already a limit for many years, between 4 and 20 characters: https://github.com/movim/movim_api/blob/master/app/Http/Controllers/AccountsController.php#L202 

So I really don't get how you did it

**Comment by RedSnt** [comment]
> So I really don't get how you did it

Generated password with KeePassXC then simply pasted it into the password field. I guess there's no check when pasting the PW directly into the fields?

**Comment by edhelas** [comment]
Ah yes sorry, the limit was on username, not password. I guess I'll put a upper limit there as well.

**Comment by edhelas** [comment]
Fixed in https://github.com/movim/movim_api/commit/185a8841fd63de44de1f40030cf2bd9b0b48f19b

**Comment by RedSnt** [comment]
@edhelas I'm glad a bug was found, but my main issue still remain: Can't create an account because that email exists somewhere in a movim database and I'm not getting any emails to recover it. Lost in limbo.

<details>
<summary>Vid of still being locked out.</summary>

https://github.com/user-attachments/assets/9926b7a0-0575-4f7a-ab15-0ac231191a3d

</details>

**Comment by edhelas** [comment]
Account deleted, you can try again

**Comment by RedSnt** [comment]
I simply got a `bad request` error, the same as originally. Does the password not recognize exclamation marks? Or is it because my email has capital letters in it?  

<details>
<summary>Screenshot of bad request error msg.</summary>

![Image](https://github.com/user-attachments/assets/c71b354b-f1ce-4559-adba-72d930e68e1a)

</details>
