### ISSUE TITLE
MySQL migration issue

### ISSUE THREAD

**Issue by Strouroul** [movim/movim#1426]
so i cloned this repo
then did
composer install

then

```
composer movim:migrate

    vendor/bin/phinx migrate --ansi
    Phinx by CakePHP - https://phinx.org/.

using config file phinx.php
using config parser php
using migration paths

    /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations
    using seed paths
    warning no environment specified, defaulting to: movim
    using adapter mysql
    using database movim
    ordering by creation time

== 20180314212906 CreateUrlsTable: migrating
== 20180314212906 CreateUrlsTable: migrated 2.3271s

== 20180314222244 CreateConfigurationTable: migrating
== 20180314222244 CreateConfigurationTable: migrated 1.1253s

== 20180316170924 CreateUsersTable: migrating
== 20180316170924 CreateUsersTable: migrated 1.1731s

== 20180316172639 CreateSessionsTable: migrating
== 20180316172639 CreateSessionsTable: migrated 5.0960s

== 20180317080249 CreatePresencesTable: migrating
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:571
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(571): PDOStatement->execute()
https://github.com/movim/movim/issues/1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(812): Illuminate\Database\Connection->Illuminate\Database{closure}()
https://github.com/movim/movim/issues/2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
https://github.com/movim/movim/issues/3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
https://github.com/movim/movim/pull/4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
https://github.com/movim/movim/pull/5 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
https://github.com/movim/movim/issues/6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(418): Illuminate\Database\Schema\Builder->build()
https://github.com/movim/movim/issues/7 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20180317080249_create_presences_table.php(10): Illuminate\Database\Schema\Builder->create()
https://github.com/movim/movim/issues/8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): CreatePresencesTable->up()
https://github.com/movim/movim/issues/9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
https://github.com/movim/movim/pull/10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
https://github.com/movim/movim/issues/11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
https://github.com/movim/movim/issues/12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
https://github.com/movim/movim/issues/13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
https://github.com/movim/movim/issues/14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
https://github.com/movim/movim/issues/15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
https://github.com/movim/movim/pull/16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
https://github.com/movim/movim/issues/17 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
https://github.com/movim/movim/issues/18 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
https://github.com/movim/movim/issues/19 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead (Connection: default, SQL: create table presences (session_id varchar(32) not null, jid varchar(64) not null, resource varchar(128) null, value int not null, priority int not null, status varchar(255) null, node varchar(255) null, delay datetime null, last int null, muc tinyint(1) not null, mucjid varchar(255) null, mucaffiliation varchar(32) null, mucrole varchar(32) null, created_at timestamp null, updated_at timestamp null, primary key (session_id, jid, resource)) default character set utf8mb4 collate 'utf8mb4_bin') in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:825
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
https://github.com/movim/movim/issues/1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
https://github.com/movim/movim/issues/2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
https://github.com/movim/movim/issues/3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
https://github.com/movim/movim/pull/4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(418): Illuminate\Database\Schema\Builder->build()
https://github.com/movim/movim/pull/5 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20180317080249_create_presences_table.php(10): Illuminate\Database\Schema\Builder->create()
https://github.com/movim/movim/issues/6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): CreatePresencesTable->up()
https://github.com/movim/movim/issues/7 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
https://github.com/movim/movim/issues/8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
https://github.com/movim/movim/issues/9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
https://github.com/movim/movim/pull/10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
https://github.com/movim/movim/issues/11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
https://github.com/movim/movim/issues/12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
https://github.com/movim/movim/issues/13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
https://github.com/movim/movim/issues/14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
https://github.com/movim/movim/issues/15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
https://github.com/movim/movim/pull/16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
https://github.com/movim/movim/issues/17 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$

.env file
Database configuration

#DB_DRIVER=pgsql
DB_DRIVER=mysql
DB_HOST=mysql.domain.com
DB_PORT=3306
DB_DATABASE=movim
DB_USERNAME=dbusername
DB_PASSWORD=dbpassword
Daemon configuration

DAEMON_URL=https://movim.domain.com/ # Public URL of your Movim instance
DAEMON_PORT=8283 # Port on which the daemon will listen
DAEMON_INTERFACE=192.168.0.80 # Interface on which the daemon will listen, must be an IP
DAEMON_DEBUG=false
DAEMON_VERBOSE=false
```

**Comment by edhelas** [comment]
No need to yell, I'll not work faster and I have notifications on the issues.
I've pushed a fix in the other ticket.

Also you can try to use "```" around your pasted code next time, helps with the formating and readibility of the tickets.

**Comment by Strouroul** [comment]
i see the the ticket it was closed but im still getting the same error ?

i can never get past composer movim:migrate to be able to get this running

**Comment by edhelas** [comment]
I made another fix, pull and try again

**Comment by Strouroul** [comment]
so i did pull again and tried it stops at a different part now

```
" composer movim:migrate
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations
using seed paths
warning no environment specified, defaulting to: movim
using adapter mysql
using database movim
ordering by creation time

 == 20180314212906 CreateUrlsTable: migrating
 == 20180314212906 CreateUrlsTable: migrated 0.6597s

 == 20180314222244 CreateConfigurationTable: migrating
 == 20180314222244 CreateConfigurationTable: migrated 0.7979s

 == 20180316170924 CreateUsersTable: migrating
 == 20180316170924 CreateUsersTable: migrated 0.7450s

 == 20180316172639 CreateSessionsTable: migrating
 == 20180316172639 CreateSessionsTable: migrated 3.2531s

 == 20180317080249 CreatePresencesTable: migrating
 == 20180317080249 CreatePresencesTable: migrated 2.3659s

 == 20180317171123 CreateContactsTable: migrating
 == 20180317171123 CreateContactsTable: migrated 0.8767s

 == 20180318222026 CreateCachesTable: migrating
 == 20180318222026 CreateCachesTable: migrated 3.3647s

 == 20180322203855 CreateRostersTable: migrating
 == 20180322203855 CreateRostersTable: migrated 2.6768s

 == 20180324134149 CreateEncryptedPasswordsTable: migrating
 == 20180324134149 CreateEncryptedPasswordsTable: migrated 2.7102s

 == 20180324145150 CreateCapabilitiesTable: migrating
 == 20180324145150 CreateCapabilitiesTable: migrated 0.8214s

 == 20180325161414 CreateConferencesTable: migrating
 == 20180325161414 CreateConferencesTable: migrated 2.8306s

 == 20180327203201 CreateMessagesTable: migrating
 == 20180327203201 CreateMessagesTable: migrated 2.8321s

 == 20180401144542 CreateInvitesTable: migrating
 == 20180401144542 CreateInvitesTable: migrated 2.6577s

 == 20180401212130 CreateInfosTable: migrating
 == 20180401212130 CreateInfosTable: migrated 2.0956s

 == 20180402112838 CreateSubscriptionsTable: migrating
 == 20180402112838 CreateSubscriptionsTable: migrated 2.6932s

 == 20180402145559 CreatePostsTable: migrating
 == 20180402145559 CreatePostsTable: migrated 4.1322s

 == 20180402145603 CreateTagsTable: migrating
 == 20180402145603 CreateTagsTable: migrated 8.0278s

 == 20180503215606 ChangeLengthColumnsInfoPresence: migrating
 == 20180503215606 ChangeLengthColumnsInfoPresence: migrated 1.9777s

 == 20180506173115 AddVcardUpdateToPresence: migrating
 == 20180506173115 AddVcardUpdateToPresence: migrated 1.2568s

 == 20180510141439 ChangeLengthContactsId: migrating
 == 20180510141439 ChangeLengthContactsId: migrated 11.9159s

 == 20180515205626 ChangeMessagesPrimaryKey: migrating
 == 20180515205626 ChangeMessagesPrimaryKey: migrated 5.7300s

 == 20180529103706 AddRelatedToInfos: migrating
 == 20180529103706 AddRelatedToInfos: migrated 1.4904s

 == 20180606155549 AddJidtoAndTypeIndexesToMessages: migrating
 == 20180606155549 AddJidtoAndTypeIndexesToMessages: migrated 1.0969s

 == 20180612215122 UpdateUniqueConstraintSessions: migrating
 == 20180612215122 UpdateUniqueConstraintSessions: migrated 0.9101s

 == 20180618212639 AddCategoryAndRelIndexesToAttachments: migrating
 == 20180618212639 AddCategoryAndRelIndexesToAttachments: migrated 1.2647s

 == 20180628203853 AddIndexesPresencesPostsMessagesTables: migrating
 == 20180628203853 AddIndexesPresencesPostsMessagesTables: migrated 4.9263s

 == 20180716200312 SetUpSqlite: migrating
 == 20180716200312 SetUpSqlite: migrated 0.1662s

 == 20180807210349 AddItemsToInfosTable: migrating
 == 20180807210349 AddItemsToInfosTable: migrated 2.1475s

 == 20180817064720 AddReplaceIdToMessagesTable: migrating
 == 20180817064720 AddReplaceIdToMessagesTable: migrated 2.9366s

 == 20180819185529 AddContentHashToPostsTable: migrating
 == 20180819185529 AddContentHashToPostsTable: migrated 2.1224s

 == 20180901223936 AddCategoryTypeIndexesToInfosAndCapabilitiesTable: migrating
 == 20180901223936 AddCategoryTypeIndexesToInfosAndCapabilitiesTable: migrated 1.9645s

 == 20180917210101 AddUniquePostIdHashToAttachmentsTable: migrating
 == 20180917210101 AddUniquePostIdHashToAttachmentsTable: migrated 0.7889s

 == 20181006212023 RemoveEditedMessagesTable: migrating
 == 20181006212023 RemoveEditedMessagesTable: migrated 3.5174s

 == 20181129220755 AddMucSemiAnonymousToInfosTable: migrating
 == 20181129220755 AddMucSemiAnonymousToInfosTable: migrated 1.8227s

 == 20190124220622 AddAvatarHashInfosTable: migrating
 == 20190124220622 AddAvatarHashInfosTable: migrated 1.7651s

 == 20190214103122 RemoveThemeFromConfigurationTable: migrating
 == 20190214103122 RemoveThemeFromConfigurationTable: migrated 1.4442s

 == 20190224220950 ChangeLengthColumnsConferencesRostersUsers: migrating
 == 20190224220950 ChangeLengthColumnsConferencesRostersUsers: migrated 5.9826s

 == 20190310102930 AddNicknameToUsersTable: migrating
 == 20190310102930 AddNicknameToUsersTable: migrated 2.9846s

 == 20190324190611 CreateReactionsTable: migrating
 == 20190324190611 CreateReactionsTable: migrated 9.9142s

 == 20190503110908 ClearAvatarHashContactsTable: migrating
 == 20190503110908 ClearAvatarHashContactsTable: migrated 0.1774s

 == 20190514162951 AddSeenToMessagesTable: migrating
 == 20190514162951 AddSeenToMessagesTable: migrated 2.1554s

 == 20190625074929 ChangeHrefTypeAttachementsTable: migrating
 == 20190625074929 ChangeHrefTypeAttachementsTable: migrated 0.1104s

 == 20190713155258 ChangeLengthEmojiReactionsTable: migrating
 == 20190713155258 ChangeLengthEmojiReactionsTable: migrated 0.2885s

 == 20190722083613 AddChatMainToUsersTable: migrating
 == 20190722083613 AddChatMainToUsersTable: migrated 1.4213s

 == 20190806211100 AddPubsubPublishAccessModelToInfosTable: migrating
 == 20190806211100 AddPubsubPublishAccessModelToInfosTable: migrated 4.1622s

 == 20190827105542 AddIndexUserIdToMessages: migrating
 == 20190827105542 AddIndexUserIdToMessages: migrated 0.7325s

 == 20191017214225 CreateIdentitiesTable: migrating
 == 20191017214225 CreateIdentitiesTable: migrated 16.1474s

 == 20191123175309 AddIndexAvatarhashToContactsTable: migrating
 == 20191123175309 AddIndexAvatarhashToContactsTable: migrated 0.8273s

 == 20191124221610 ClearBuggyPubsubNodesInInfosTable: migrating
 == 20191124221610 ClearBuggyPubsubNodesInInfosTable: migrated 0.1045s

 == 20191223125342 AddChatOnlyToConfigurationTable: migrating
 == 20191223125342 AddChatOnlyToConfigurationTable: migrated 1.2439s

 == 20200105125952 AddEncryptedToMessagesTable: migrating
 == 20200105125952 AddEncryptedToMessagesTable: migrated 2.5660s

 == 20200126181331 AddOriginIdToMessagesTable: migrating
 == 20200126181331 AddOriginIdToMessagesTable: migrated 6.8848s

 == 20200305220107 RemoveCssurlUsersTable: migrating
 == 20200305220107 RemoveCssurlUsersTable: migrated 2.5508s

 == 20200327114708 AddNotificationsToUsersTable: migrating
 == 20200327114708 AddNotificationsToUsersTable: migrated 2.9662s

 == 20200414191641 AddResolvedToMessagesTable: migrating
 == 20200414191641 AddResolvedToMessagesTable: migrated 3.1866s

 == 20200419103403 AddExternalServicesToSessionsTable: migrating
 == 20200419103403 AddExternalServicesToSessionsTable: migrated 1.7771s

 == 20200422151151 RemoveExternalServicesToSessionsTable: migrating
 == 20200422151151 RemoveExternalServicesToSessionsTable: migrated 1.6434s

 == 20200505175149 AddIdIndexToMessages: migrating
 == 20200505175149 AddIdIndexToMessages: migrated 0.4989s

 == 20200505213814 AddAvatarRequestedToContactsTable: migrating
 == 20200505213814 AddAvatarRequestedToContactsTable: migrated 1.8659s

 == 20200514143915 ChangePictureTypeMessagesTable: migrating
 == 20200514143915 ChangePictureTypeMessagesTable: migrated 5.5865s

 == 20200524135852 AddIdleToPresencesTable: migrating
 == 20200524135852 AddIdleToPresencesTable: migrated 1.6328s

 == 20200626090432 AddParentToInfosTable: migrating
 == 20200626090432 AddParentToInfosTable: migrated 4.1148s

 == 20200714184243 AddNotifyAndExtensionsToConferencesTable: migrating
 == 20200714184243 AddNotifyAndExtensionsToConferencesTable: migrated 4.8409s

 == 20201005202613 CreateMembersTable: migrating
 == 20201005202613 CreateMembersTable: migrated 3.7428s

 == 20201031170045 AddParentThreadToMessagesTable: migrating
 == 20201031170045 AddParentThreadToMessagesTable: migrated 3.1659s

 == 20201106101328 AddParentMidToMessagesTable: migrating
 == 20201106101328 AddParentMidToMessagesTable: migrated 7.0510s

 == 20201113083847 AddIndexJidToRostersTable: migrating
 == 20201113083847 AddIndexJidToRostersTable: migrated 0.7313s

 == 20201115100615 SetCaseSensitiveResourceTablePresences: migrating
 == 20201115100615 SetCaseSensitiveResourceTablePresences: migrated 2.0113s

 == 20201115155237 AddIndexAidToPostsTable: migrating
 == 20201115155237 AddIndexAidToPostsTable: migrated 0.4663s

 == 20201128214540 AddIndexParentmidToMessagesTable: migrating
 == 20201128214540 AddIndexParentmidToMessagesTable: migrated 0.7800s

 == 20201203221412 AddGifapikeyToConfigurationTable: migrating
 == 20201203221412 AddGifapikeyToConfigurationTable: migrated 1.3517s

 == 20201222194330 AddAutoincrementToUrlsTable: migrating
 == 20201222194330 AddAutoincrementToUrlsTable: migrated 7.1790s

 == 20210113190348 DropUnusedIndexes: migrating
 == 20210113190348 DropUnusedIndexes: migrated 1.4423s

 == 20210118230910 RemoveJidForeignFromMembersTable: migrating
 == 20210118230910 RemoveJidForeignFromMembersTable: migrated 0.3596s

 == 20210120213740 AddFirebaseauthorizationkeyToConfigurationTable: migrating
 == 20210120213740 AddFirebaseauthorizationkeyToConfigurationTable: migrated 1.3835s

 == 20210302212105 AddDisableRegistratonToConfigurationTable: migrating
 == 20210302212105 AddDisableRegistratonToConfigurationTable: migrated 1.3333s

 == 20210315212642 ChangeNameTypeConferencesTable: migrating
 == 20210315212642 ChangeNameTypeConferencesTable: migrated 1.7890s

 == 20210329190212 CreateDraftsTable: migrating
 == 20210329190212 CreateDraftsTable: migrated 5.3128s

 == 20210420201638 AddOriginIdIndexToMessagesTable: migrating
 == 20210420201638 AddOriginIdIndexToMessagesTable: migrated 0.5782s

 == 20210425191845 AddOmemoHeaderToMessagesTable: migrating
 == 20210425191845 AddOmemoHeaderToMessagesTable: migrated 4.6803s

 == 20210510204138 AddAdminColumnToUsersTable: migrating
 == 20210510204138 AddAdminColumnToUsersTable: migrated 6.7576s

 == 20210526164828 CreateBundlesTable: migrating
 == 20210526164828 CreateBundlesTable: migrated 4.1763s

 == 20210805181846 AddPinnedToConferencesTable: migrating
 == 20210805181846 AddPinnedToConferencesTable: migrated 1.9112s

 == 20210922192725 AddBundleIdToMessagesTable: migrating
 == 20210922192725 AddBundleIdToMessagesTable: migrated 5.2743s

 == 20210922194637 AddBundleIdDeviceIdUniqueToBundleSessionsTable: migrating
 == 20210922194637 AddBundleIdDeviceIdUniqueToBundleSessionsTable: migrated 2.4107s

 == 20211201192240 AddNodeToBundlesTable: migrating
 == 20211201192240 AddNodeToBundlesTable: migrated 1.6590s

 == 20211205192024 UpgradePictureSha256: migrating
 == 20211205192024 UpgradePictureSha256: migrated 0.2076s

 == 20220105200846 DropBundleSessionsTable: migrating
 == 20220105200846 DropBundleSessionsTable: migrated 0.6006s

 == 20220126214606 TruncateContactTable: migrating
 == 20220126214606 TruncateContactTable: migrated 1.1179s

 == 20220211130127 RemoveXmppCountryFromConfigurationTable: migrating
 == 20220211130127 RemoveXmppCountryFromConfigurationTable: migrated 1.5037s

 == 20220406184943 CreatePushSubscriptionsTable: migrating
 == 20220406184943 CreatePushSubscriptionsTable: migrated 3.8108s

 == 20220722133156 AddTwitterTokenToConfigurationTable: migrating
 == 20220722133156 AddTwitterTokenToConfigurationTable: migrated 2.4512s

 == 20220801205253 CreateReportedTable: migrating
 == 20220801205253 CreateReportedTable: migrated 8.7671s

 == 20220904214010 AddEnabledAndBrowserVersionToPushSubscriptionsTable: migrating
 == 20220904214010 AddEnabledAndBrowserVersionToPushSubscriptionsTable: migrated 3.0016s

 == 20221018204916 AddMessageIdAndStanzaIdToMessagesTable: migrating
 == 20221018204916 AddMessageIdAndStanzaIdToMessagesTable: migrated 9.1981s

 == 20221030124556 AddPhoneToContactsTable: migrating
 == 20221030124556 AddPhoneToContactsTable: migrated 1.4774s

 == 20221114210820 AddBannerHashToContactsTable: migrating
 == 20221114210820 AddBannerHashToContactsTable: migrated 1.7668s

 == 20221115220935 AddActivityAtColumnToPushSubscriptionsTable: migrating
 == 20221115220935 AddActivityAtColumnToPushSubscriptionsTable: migrated 1.6549s

 == 20221204113418 UpdateCreatedAtNotNullInPushSubscriptionsTable: migrating
 == 20221204113418 UpdateCreatedAtNotNullInPushSubscriptionsTable: migrated 2.6081s

 == 20221224102134 AddAvatarTypeToContactsTable: migrating
 == 20221224102134 AddAvatarTypeToContactsTable: migrated 2.0413s

 == 20230303224825 AddTypeToInfosTable: migrating
 == 20230303224825 AddTypeToInfosTable: migrated 3.3859s

 == 20230318150507 SetCorrectCollationEmojiToReactionsTable: migrating
 == 20230318150507 SetCorrectCollationEmojiToReactionsTable: migrated 1.8451s

 == 20230321201405 SetCorrectCollationToAllTables: migrating
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1157:

  The process "vendor/bin/phinx migrate --ansi" exceeded the timeout of 300 s
  econds.


movim:migrate [--dev] [--no-dev] [--] [<args>...]

haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$  == 20230321201405 SetCorrectCollationToAllTables: migrated 8.5714s

 == 20230507155205 AddOmemoenabledToUserTable: migrating
 == 20230507155205 AddOmemoenabledToUserTable: migrated 1.9320s

 == 20230612194157 CreatePostUserViewsTable: migrating
 == 20230612194157 CreatePostUserViewsTable: migrated 6.3002s

 == 20230705180628 AddIndexUseridSeenTypeJidfromToMessagesTable: migrating
 == 20230705180628 AddIndexUseridSeenTypeJidfromToMessagesTable: migrated 0.8234s

 == 20231014161444 CreateAffiliationsTable: migrating
 == 20231014161444 CreateAffiliationsTable: migrated 3.6854s

 == 20231108190801 AddReactionsRestrictionsToInfosTable: migrating
 == 20231108190801 AddReactionsRestrictionsToInfosTable: migrated 2.0891s

 == 20231211172456 DropTwitterTokenFromConfigurationTable: migrating
 == 20231211172456 DropTwitterTokenFromConfigurationTable: migrated 3.7481s

 == 20231212213544 AddSyncedToReportedUserTable: migrating
 == 20231212213544 AddSyncedToReportedUserTable: migrated 1.7876s

 == 20240204122606 AddCommentsDisabledToDrafsTable: migrating
 == 20240204122606 AddCommentsDisabledToDrafsTable: migrated 1.8332s

 == 20240306164458 AddTypeToSessionsTable: migrating
 == 20240306164458 AddTypeToSessionsTable: migrated 1.6773s

 == 20240605155217 CreateMessageFilesTable: migrating
 == 20240605155217 CreateMessageFilesTable: migrated 8.5910s

 == 20240616151744 CreateUploadTable: migrating
 == 20240616151744 CreateUploadTable: migrated 8.4557s

 == 20240709210232 AddInlinesToMessagesTable: migrating
 == 20240709210232 AddInlinesToMessagesTable: migrated 3.2461s

 == 20240718073640 CreateEmojisTable: migrating
 == 20240718073640 CreateEmojisTable: migrated 13.5931s

 == 20240718161138 CreateStickersTable: migrating
 == 20240718161138 CreateStickersTable: migrated 19.4257s

 == 20240806195930 AddTypeToPresencesTable: migrating
 == 20240806195930 AddTypeToPresencesTable: migrated 1.9143s

 == 20240821222033 AddCascadeOnUsersSessionsForeignKey: migrating
 == 20240821222033 AddCascadeOnUsersSessionsForeignKey: migrated 0.5888s

 == 20240822195639 DropCachesTable: migrating
 == 20240822195639 DropCachesTable: migrated 8.8779s

 == 20240827184020 ChangeEncryptedPasswordsUserIdLength: migrating
 == 20240827184020 ChangeEncryptedPasswordsUserIdLength: migrated 0.8338s

 == 20240911061937 AddHashToMessageFilesTable: migrating
PDOException: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'message_files_message_mid_url_size_unique': needed in a foreign key constraint in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:571
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(571): PDOStatement->execute()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20240911061937_add_hash_to_message_files_table.php(13): Illuminate\Database\Schema\Builder->table()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): AddHashToMessageFilesTable->up()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#17 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#19 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'message_files_message_mid_url_size_unique': needed in a foreign key constraint (Connection: default, SQL: alter table `message_files` drop index `message_files_message_mid_url_size_unique`) in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:825
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20240911061937_add_hash_to_message_files_table.php(13): Illuminate\Database\Schema\Builder->table()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): AddHashToMessageFilesTable->up()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#17 {main}


 php daemon.php start

The database needs to be migrated before running the daemon
To migrate the database run
php vendor/bin/phinx migrate
haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$ ^C
haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$ php vendor/bin/phinx migrate
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations
using seed paths
warning no environment specified, defaulting to: movim
using adapter mysql
using database movim
ordering by creation time

 == 20240911061937 AddHashToMessageFilesTable: migrating
PDOException: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'message_files_message_mid_url_size_unique': needed in a foreign key constraint in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:571
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(571): PDOStatement->execute()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20240911061937_add_hash_to_message_files_table.php(13): Illuminate\Database\Schema\Builder->table()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): AddHashToMessageFilesTable->up()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#17 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#19 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'message_files_message_mid_url_size_unique': needed in a foreign key constraint (Connection: default, SQL: alter table `message_files` drop index `message_files_message_mid_url_size_unique`) in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:825
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20240911061937_add_hash_to_message_files_table.php(13): Illuminate\Database\Schema\Builder->table()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): AddHashToMessageFilesTable->up()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#17 {main}
haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$


"

```

**Comment by edhelas** [comment]
Reformat the content, change the title to something a bit more serious

**Comment by edhelas** [comment]
Can you please give me your MySQL flavour and version exactly ?

**Comment by Strouroul** [comment]
> Can you please give me your MySQL flavour and version exactly ?

MySQL : 8.0.41 (deb MySQL Package for Ubuntu 24.04)

still i did a git pull to the repo

then
"
 composer movim:migrate
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations
using seed paths
warning no environment specified, defaulting to: movim
using adapter mysql
using database movim
ordering by creation time

 == 20240911061937 AddHashToMessageFilesTable: migrating
 == 20240911061937 AddHashToMessageFilesTable: migrated 6.7906s

 == 20241010182000 AddTimezoneToSessionsTable: migrating
 == 20241010182000 AddTimezoneToSessionsTable: migrated 1.8805s

 == 20241023191530 UpdateTitleUpdatedNotNullPostsTable: migrating
 == 20241023191530 UpdateTitleUpdatedNotNullPostsTable: migrated 4.0523s

 == 20241204113047 AddPostIdToMessagesTable: migrating
 == 20241204113047 AddPostIdToMessagesTable: migrated 4.1317s

 == 20250109192438 AddMucjidPresencesPrimaryKey: migrating
 == 20250109192438 AddMucjidPresencesPrimaryKey: migrated 0.1108s

 == 20250122171213 DropPresencesPrimaryKeyForHashColumn: migrating
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:571
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(571): PDOStatement->execute()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(812): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20250122171213_drop_presences_primary_key_for_hash_column.php(19): Illuminate\Database\Schema\Builder->table()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): DropPresencesPrimaryKeyForHashColumn->up()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#17 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#19 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (Connection: default, SQL: alter table `presences` add `hash` varchar(255) character set binary as (sha2(concat_ws('|', session_id, jid, mucjid, resource), 256)) stored) in /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php:825
Stack trace:
#0 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#1 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Connection.php(560): Illuminate\Database\Connection->run()
#2 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Blueprint.php(118): Illuminate\Database\Connection->statement()
#3 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#4 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/illuminate/database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build()
#5 /mnt/RIG1_E_DRIVE/inetpub/movim/database/migrations/20250122171213_drop_presences_primary_key_for_hash_column.php(19): Illuminate\Database\Schema\Builder->table()
#6 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): DropPresencesPrimaryKeyForHashColumn->up()
#7 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#8 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#9 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#10 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#11 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#12 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#14 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#15 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 /mnt/RIG1_E_DRIVE/inetpub/movim/vendor/bin/phinx(119): include('...')
#17 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
haytham@RIG1:/mnt/RIG1_E_DRIVE/inetpub/movim$

"


this stopped at a different part
